In [16]:
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras

In [32]:
help(keras.metrics.Accuracy)

Help on class Accuracy in module tensorflow.python.keras.metrics:

class Accuracy(MeanMetricWrapper)
 |  Accuracy(*args, **kwargs)
 |  
 |  Calculates how often predictions equals labels.
 |  
 |  This metric creates two local variables, `total` and `count` that are used to
 |  compute the frequency with which `y_pred` matches `y_true`. This frequency is
 |  ultimately returned as `binary accuracy`: an idempotent operation that simply
 |  divides `total` by `count`.
 |  
 |  If `sample_weight` is `None`, weights default to 1.
 |  Use `sample_weight` of 0 to mask values.
 |  
 |  Args:
 |    name: (Optional) string name of the metric instance.
 |    dtype: (Optional) data type of the metric result.
 |  
 |  Standalone usage:
 |  
 |  >>> m = tf.keras.metrics.Accuracy()
 |  >>> m.update_state([[1], [2], [3], [4]], [[0], [2], [3], [4]])
 |  >>> m.result().numpy()
 |  0.75
 |  
 |  >>> m.reset_states()
 |  >>> m.update_state([[1], [2], [3], [4]], [[0], [2], [3], [4]],
 |  ...              

In [9]:
acc = keras.metrics.Accuracy()
acc([0,1], [1,1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [10]:
acc([1,1,1], [1,1,1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.8>

In [11]:
acc.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.8>

In [12]:
acc.variables

[<tf.Variable 'total:0' shape=() dtype=float32, numpy=4.0>,
 <tf.Variable 'count:0' shape=() dtype=float32, numpy=5.0>]

In [13]:
acc.reset_states()
acc

In [14]:
acc.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [22]:
n_instances = 6000
n_classes = 9
arti_true = np.zeros((n_instances, n_classes))
arti_true[range(n_instances), np.random.randint(0, n_classes, size=(n_instances,))] = 1
arti_pred = np.random.rand(*(arti_true.shape))
arti_pred.shape

(6000, 9)

In [23]:
arti_pred[:5]

array([[0.12480857, 0.56199306, 0.31504689, 0.21181823, 0.18778424,
        0.23606456, 0.8887163 , 0.59304955, 0.63571288],
       [0.35324434, 0.64407214, 0.6035343 , 0.20503036, 0.21099545,
        0.83079467, 0.80243566, 0.98401888, 0.07154428],
       [0.35565178, 0.11787194, 0.61118288, 0.07989535, 0.20293937,
        0.89929858, 0.08474662, 0.51401549, 0.66943547],
       [0.49253283, 0.31326617, 0.50111813, 0.28994736, 0.72222158,
        0.03781726, 0.1288525 , 0.73605137, 0.98371653],
       [0.56104435, 0.35761733, 0.01507624, 0.57976774, 0.0719467 ,
        0.85055736, 0.73032486, 0.06958508, 0.90544197]])

In [25]:
arti_true[:5]

array([[0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
help(tf.maximum)

Help on function maximum in module tensorflow.python.ops.gen_math_ops:

maximum(x, y, name=None)
    Returns the max of x and y (i.e. x > y ? x : y) element-wise.
    
    Example:
    >>> x = tf.constant([0., 0., 0., 0.])
    >>> y = tf.constant([-2., 0., 2., 5.])
    >>> tf.math.maximum(x, y)
    <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 0., 2., 5.], dtype=float32)>
    
    Args:
      x: A `Tensor`. Must be one of the following types: `bfloat16`, `half`, `float32`, `float64`, `uint8`, `int16`, `int32`, `int64`.
      y: A `Tensor`. Must have the same type as `x`.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor`. Has the same type as `x`.



In [30]:
arti_true[:5]

array([[0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
tf.argmax(arti_true[:5], axis=1)

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([3, 8, 4, 0, 0])>